### ISSUE TITLE
ban/unban aren't working

### ISSUE THREAD

**Issue by alsoGAMER** [alsoGAMER/BotBase#3]
By sending /ban ID the bot will say "✅ User banned successfully" to the admin and "❌ You've been banned" to that user, but checking the `banned` field will be 0 (False)

So by sending /unban ID, the bot will say "❌ This user isn't banned" even if that user can't actually use the bot (none of the commands and buttons works)

**Comment by nocturn9x** [comment]
@alsoGAMER I think we should use BOOLEAN instead of INT in mysql (or at least TINYINT)

**Comment by kuogitg** [comment]
@nocturn9x a

**Comment by alsoGAMER** [comment]
I tried to use BOOLEAN for that field, but MySQL is dumb and will auto-convert the type during the query execution
Update 19:42 GMT+1: I've set the field type to TINYINT but the issue is still here
